### ISSUE TITLE
Remove the long-deprecated "b64" attribute on random_id

### ISSUE THREAD

**Issue by apparentlymart** [hashicorp/terraform-provider-random#10]
The `b64` attribute of `random_id` was deprecated in late 2016 in favor of `b64_url` and `b64_std` alternatives that give two variants with different base64 digit sets.

`b64` has been deprecated (and undocumented) for long enough now that we can remove it for the next major release.

**Comment by bbnathan** [comment]
Is there a recommendation for migrating existing state? The 3.0.0 release has broken pretty much all of our pipelines:

`
 Error: Invalid resource instance data in state
   on modules/global/main.tf line 1:
    1: resource "random_id" "id" {

 Instance module.global.random_id.id data could not be decoded from the state: unsupported attribute "b64".
`
