### ISSUE TITLE
Error: rpc error: code = Unavailable desc = transport is closing

### ISSUE THREAD

**Issue by ericrichtert** [hashicorp/terraform-provider-random#105]
### Terraform Version
Terraform v0.12.24
+ provider.aws v2.53.0
+ provider.random v2.2.1
+ provider.template v2.1.2

### Affected Resource(s)
resource "random_password" "xxx_yyy_password" {
  length           = 1
  min_numeric      = 1
  min_lower        = 1
  min_upper        = 1
  min_special      = 1
  override_special = "!#*()-_=+[]{}<>:?"

  keepers = {
    # Generate a new id each time we create a new RDS instance
    db_name = var.db_name
  }
}

### Expected Behavior
No error

### Actual Behavior
Error: rpc error: code = Unavailable desc = transport is closing

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
The thing seems to be the length of the password. When I set it to 15, there seems to be issue.

**Comment by bendbennett** [comment]
@ericrichtert apologies for the delay in getting to this issue.
Assuming you are still using `v0.12.x` of Terraform, can you confirm whether you are seeing this issue with TF `v0.12.31` and  `v3.3.2` of the random provider?

**Comment by bflad** [comment]
Closing due to lack of response. If you are still having an issue, please open a new issue and we will take a fresh look. Thanks!
