### ISSUE TITLE
random_string resource prints warning during plan

### ISSUE THREAD

**Issue by ryboe** [hashicorp/terraform-provider-random#112]
### Terraform Version
Terraform v0.12.24
+ provider.google v3.19.0
+ provider.google-beta v3.19.0
+ provider.random v2.2.1
+ provider.tfe v0.16.0

### Affected Resource(s)

- random_string

### Terraform Configuration Files

```hcl
resource "random_string" "four_chars" {
  length  = 4
  upper   = false
  special = false
}
```

### Debug Output

```
2020/04/27 12:10:56 [WARN] Provider "registry.terraform.io/-/random" produced an invalid plan for module.db.random_string.four_chars, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .min_lower: planned value cty.NumberIntVal(0) does not match config value cty.NullVal(cty.Number)
      - .min_numeric: planned value cty.NumberIntVal(0) does not match config value cty.NullVal(cty.Number)
      - .min_special: planned value cty.NumberIntVal(0) does not match config value cty.NullVal(cty.Number)
      - .lower: planned value cty.True does not match config value cty.NullVal(cty.Bool)
      - .min_upper: planned value cty.NumberIntVal(0) does not match config value cty.NullVal(cty.Number)
      - .number: planned value cty.True does not match config value cty.NullVal(cty.Bool)
```
### Expected Behavior

The plan should've run without any warnings.

### Actual Behavior

The plan produced the warning above.

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

This is being using with Google Cloud.

**Comment by y0ssar1an** [comment]
Apparently, [these warnings have something to do with the v0.12 migration](https://discuss.hashicorp.com/t/context-around-the-log-entry-tolerating-it-because-it-is-using-the-legacy-plugin-sdk/1630). I don't understand what the issue is. Shouldn't providers maintained by Hashicorp be free of warnings?

**Comment by bendbennett** [comment]
@ryboe apologies for the delay in getting to this issue.
Assuming you are still using `v0.12.x` of Terraform, do you still see the same warnings after upgrading to `v0.12.31`?

**Comment by ryboe** [comment]
I'll close this issue since I no longer can tell if it's still an issue.
