### ISSUE TITLE
no available releases match the given constraints 3.0.0, ~> 2.2, ~> 2.2

### ISSUE THREAD

**Issue by syedrakib** [hashicorp/terraform-provider-random#123]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
v0.13.4

### Affected Resource(s)
- `random_string`

### Terraform Configuration Files
```hcl
provider "random" {
  version = "3.0.0" # See https://github.com/hashicorp/terraform-provider-random/releases
}

```

### Debug Output

```
Initializing modules...

Initializing the backend...

Initializing provider plugins...
- Using previously-installed hashicorp/google v3.43.0
- Using previously-installed hashicorp/google-beta v3.43.0
- Using previously-installed hashicorp/null v2.1.2
- Using previously-installed hashicorp/kubernetes v1.13.2
- Finding hashicorp/random versions matching "3.0.0, ~> 2.2, ~> 2.2"...

Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider
hashicorp/random: no available releases match the given constraints 3.0.0, ~>
2.2, ~> 2.2
```

### Expected Behavior
The "random" provider should just install

### Actual Behavior
The "random" provider version cannot be matched. Although v3.0.0 is available in the releases - https://github.com/hashicorp/terraform-provider-random/releases

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
- `terraform init`

**Comment by paultyng** [comment]
I'm not sure whats wrong in this case, do you possibly have another version constraint somewhere else in your configuration, for example in a `terraform` block's `required_providers`?

When I run your sample file in a clean directory I get:

```
PS C:\Users\paul\sandbox\013> terraform version
Terraform v0.13.4
PS C:\Users\paul\sandbox\013> terraform init

Initializing the backend...

Initializing provider plugins...
- Finding hashicorp/random versions matching "3.0.0"...
- Installing hashicorp/random v3.0.0...
- Installed hashicorp/random v3.0.0 (signed by HashiCorp)

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
```

**Comment by snolan-uturn** [comment]
If your module uses another module that has a conflicting version requirement this will occur, so check the required_provider blocks in any modules referenced by your module. This is referred to in the docs here https://www.terraform.io/docs/configuration/provider-requirements.html#best-practices-for-provider-versions

**Comment by paultyng** [comment]
Yes, sorry I missed this above, this is the result of module version requirements being in conflict with each other or the root module. They need to agree on their constraints.
