### ISSUE TITLE
terraform-provider-random_2.3.1_linux_amd64.zip not found

### ISSUE THREAD

**Issue by hgontijo** [hashicorp/terraform-provider-random#148]
### Terraform Version
v0.13.5

### Affected Resource(s)
- random provider binary artifact

### Terraform Configuration Files
```hcl
terraform {
  required_providers {
    random = {
      source  = "hashicorp/random"
      version = "2.3.1"
    }
...
  }
  required_version = "0.13.5"
}
```

### Debug Output
Accessing the URL directly
https://releases.hashicorp.com/terraform-provider-random/2.3.1/terraform-provider-random_2.3.1_linux_amd64.zip
```
404 Not Found
    Code: NoSuchBucket
    Message: The specified bucket does not exist
    BucketName: releases.hashicorp.com
    RequestId: CF3B7C36D803DD92
    HostId: ovpJ1B6ONmDTm0fv1bO6AqYUWmB2A3+UN7U/jfp8frBYoF/wxU/+ToSHSd0Uke5v2F2LscpvVno=
```
Expected behavior while accessing URL directly would be `403 Forbidden` or direct download?

### Panic Output
```
Error: Failed to install provider
Error while installing hashicorp/random v2.3.1: unsuccessful request to
https://releases.hashicorp.com/terraform-provider-random/2.3.1/terraform-provider-random_2.3.1_linux_amd64.zip
404 Not Found
```

### Expected Behavior
Random provider to be downloaded during terraform init.

### Actual Behavior
What actually happened?

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform init`

### Important Factoids
n/a

### References
n/a

**Comment by mcristina422** [comment]
Came here looking for a solution to a similar issue, although we're using terraform 11. The bucket looks back online now though, guess it was a temporary error

**Comment by hgontijo** [comment]
Closing since it was a temporary issue.

**Comment by mcristina422** [comment]
Found this on the status page https://status.hashicorp.com/incidents/68jxtclzwn33
