### ISSUE TITLE
Rotation of random_password

### ISSUE THREAD

**Issue by ANGkeith** [hashicorp/terraform-provider-random#195]
### Use Cases or Problem Statement

I would like to request for a way to automatically generate a new `random_password` to ease secret rotation.

Here is an example of what I was able to achieve using `null_resource`
```hcl
resource "time_rotating" "example" {
  rotation_days = 1
}
resource "null_resource" "example" {
  triggers = {
    time_rotating = time_rotating.example.unix
  }
  # .... do secret rotation here
}
```

### Proposal

Was hoping that we'll be able to do something similar to the `time_rotating` resource:

```hcl
resource "random_password" "example" {
  length           = 16
  special          = false
  rotation_days    = 30
}

resource "aws_db_instance" "example" {
  instance_class    = "db.t3.micro"
  allocated_storage = 64
  engine            = "mysql"
  username          = "someone"
  password          = random_password.example.result
}

```

Thus, expected result is that every 30days, the db credentials will be rotated.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by ANGkeith** [comment]
This is the current workaround, making use of the side effect that `random_password` resource will be recreate when the `overrid_special` value is changed 

```hcl
resource "time_rotating" "example" {
  rotation_days = 1
}
resource "null_resource" "example" {
  triggers = {
    time_rotating = time_rotating.example.unix
  }
  # .... do secret rotation here
}
resource "aws_db_instance" "example" {
  instance_class    = "db.t3.micro"
  allocated_storage = 64
  engine            = "mysql"
  username          = "someone"
  password          = random_password.example.result
}
```

**Comment by Miouge1** [comment]
@ANGkeith you can use the `keepers` attribute for this purpose for example:
```
resource "time_rotating" "example" {
  rotation_minutes = 1
}
resource "random_password" "example" {
  length           = 16
  keepers = {time = time_rotating.example.id}
}
```

**Comment by ANGkeith** [comment]
Thank you, totally missed out that attributes.
