### ISSUE TITLE
trying to read variables through keepers ends up in "does not have attribute ..."

### ISSUE THREAD

**Issue by hargut** [hashicorp/terraform-provider-random#21]
Hello together,

Documentation example states that one can read a variable through the random provider:
https://www.terraform.io/docs/providers/random/r/id.html
```
  # Read the AMI id "through" the random_id resource to ensure that
  # both will change together.
  ami = "${random_id.server.keepers.ami_id}"

  # ... (other aws_instance arguments) ...
```

I tried to use keepers reading it with ${random_integer.priority.keepers.target_group_arn}, but ended up with seeing the following error:
```
* module.httpd.aws_alb_listener_rule.http: Resource 'random_integer.priority' does not have attribute 'keepers.target_group_arn' for variable random_integer.priority.keepers.target_group_arn'
```

### Terraform Version
v0.11.3

### Affected Resource(s)
Please list the resources as a list, for example:
- random_integer
Only tried with random_integer, might also effect other random_* resources.

### Terraform Configuration Files
```
resource "random_integer" "priority" {
  min = 1
  max = 50000
  keepers = {
    target_group_arn = "${aws_alb_target_group.target_group.arn}"
    route53_record_name = "${aws_route53_record.service.name}"
  }
  lifecycle {
    create_before_destroy = true
  }
}
resource "aws_alb_listener_rule" "http" {
  listener_arn = "${var.aws_services["alb_extern_http"]}"
  priority = "${random_integer.priority.result}"
  action {
    type = "forward"
    target_group_arn = "${random_integer.priority.keepers.target_group_arn}"
  }
  condition {
    field = "host-header"
    values = ["${aws_route53_record.service.name}"]
  }
}
```

### Expected Behavior
Terraform planning & applying as expected.

### Actual Behavior
Error presented as quoted above.

Many thanks in advance for your consideration. 👍 

Best regards,
Harald

**Comment by negz** [comment]
I'm currently seeing the same behaviour with `random_id`.

```
Terraform v0.11.6
+ provider.aws v1.7.0
+ provider.google v1.9.0
+ provider.ignition v1.0.0
+ provider.local v1.1.0
+ provider.random v1.2.0
+ provider.template v1.0.0
+ provider.tls v1.0.0
```

**Comment by hargut** [comment]
As I was lately comming across another issue, I was wondering if this could be related to https://github.com/hashicorp/terraform/issues/17641

**Comment by adback03** [comment]
I'm experiencing the same problem with `random_pet`.  This is with `Terraform v0.11.8` and `provider.random v2.0`.

**Comment by af6140** [comment]
Similar issue when using module output as random_id keepers var.

**Comment by 0mnius** [comment]
I found this working this way (tf v0.11.13):
with count
`ami = "${lookup(random_id.server.*.keepers[count.index], "ami_id")}"`
without
`ami = "${lookup(random_id.server.*.keepers, "ami_id")}"`

**Comment by mkam423** [comment]
Still running into this issue. A theory is that the values in the `keepers` field is expected to be constant and does not know how to handle dynamic inputs (outputs of newly created resources).

**Comment by bflad** [comment]
Hi folks 👋 There have been a large number of changes to Terraform and this particular Terraform Provider since this issue was last discussed. If you are still running into an issue with recent versions of both, please open a new issue and we will take a fresh look. Thank you.
