### ISSUE TITLE
FR: random_id should be easier to import as it may prove a challenge for users in a hurry to fix state

### ISSUE THREAD

**Issue by iamasmith** [hashicorp/terraform-provider-random#216]
### Terraform CLI and Provider Versions

Provider 3.1.1

### Use Cases or Problem Statement

Some modules routinely use random_id, particulalry Google ones to generate resources that will not clash with others.

e.g. https://github.com/terraform-google-modules/terraform-google-sql-db/blob/b73b465baabb89112958fc23c414885c02628b48/modules/mssql/main.tf#L32-L36
https://github.com/terraform-google-modules/terraform-google-sql-db/blob/b73b465baabb89112958fc23c414885c02628b48/modules/mssql/main.tf#L46

In the case of DBs this means that if one has to switch to running a cloned DB and want to import that DBs name, a portion of this will be to import the new hex value that the module created using random_id.

Assuming one had to do this under emergency situations and do it for the first time then bringing TF state inline with the new ID has the additional cognitive burden of creating something to encode the hex bytes desired into the base64 encode form of the binary bytes, whereas, the user is likely to want to recreate the hex value property quickly to match the new resource.

### Proposal

PR here https://github.com/hashicorp/terraform-provider-random/pull/215

This is a non breaking change as illustrated in the document for the resource. 

Using hex: as prefix (':' is not in the base64 dictionary) triggers the import function to encode the value from given hex provided as ascii.

Noting as shown in the document this does not break the existing prefix feature of random_id or the existing import of base64.

Very specifically prefix still looks for last index of ',' and parses that first so it is still feasible to even have a prefix of hex: if you wanted that whilst still using hex to specify the value. I don't see any other possibilities covering breakage and think this is well covered as a compatible change.

### How much impact is this issue causing?

Low

### Additional Information

Likelihood this causes a high degree of personal stress in some situations where recovery of service is a priority and one wishes to bring state inline to avoid scheduled pipeline problems with state mismatch.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bendbennett** [comment]
Closing, see https://github.com/hashicorp/terraform-provider-random/pull/215#issuecomment-1125787914
