### ISSUE TITLE
random provider returns same result with each apply/destroy cycle

### ISSUE THREAD

**Issue by pmoosh** [hashicorp/terraform-provider-random#217]
### Terraform CLI and Provider Versions

Terraform v0.14.9
provider registry.terraform.io/hashicorp/random v3.1.1

### Terraform Configuration

```terraform
resource "random_pet" "hostname" {
  length    = 2
  separator = "-"
}


output "hostname" {
  value =  random_pet.hostname

}

terraform {
  required_providers {
    random = {
      source = "hashicorp/random"
      version = "3.1.1"
    }
  }
}
```

### Expected Behavior

should return different hostname output with each apply/destroy cycle

### Actual Behavior

always returns touched-walleye

### Steps to Reproduce

1. ` terraform init'
2. `terraform apply -auto-approve`
3. `terraform destroy -auto-approve 
4.  `terraform apply -auto-approve`
5. `terraform destroy -auto-approve`

### How much impact is this issue causing?

High

### Logs

no logs

### Additional Information

this issue was introduced with version change from 3.1.0 to 3.1.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jkerry** [comment]
Sifting through the release diff the upgrade on this dependency pulled in 2 years of change and might have been unintentional:

https://github.com/hashicorp/terraform-provider-random/compare/v3.1.0...v3.1.1#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6R6
