### ISSUE TITLE
Error installing provider "random": openpgp: signature made by unknown entity

### ISSUE THREAD

**Issue by wilmanestupinan** [hashicorp/terraform-provider-random#223]
### Terraform CLI and Provider Versions

❯ terraform version
Terraform v0.11.10
+ provider registry.terraform.io/hashicorp/random v2.3.1

### Terraform Configuration

```terraform
provider "azurerm" {
  version = "=1.44.0"   
}
provider "aws" {
  version = "=2.70.0"    
}
```

### Expected Behavior

Download provider for use random for use in te project random_id

### Actual Behavior

Terraform analyses the configuration and state and automatically downloads
plugins for the providers used. However, when attempting to download this
plugin an unexpected error occured.

This may be caused if for some reason Terraform is unable to reach the
plugin repository. The repository may be unreachable if access is blocked
by a firewall.

If automatic installation is not possible or desirable in your environment,
you may alternatively manually install plugins by downloading a suitable
distribution package and placing the plugin's executable file in the
following directory:

### Steps to Reproduce

1. `terraform apply`

### How much impact is this issue causing?

High

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by FelsiyaVasanthi** [comment]
Is there any workaround for this issue till it is resolved

**Comment by wilmanestupinan** [comment]
The problem arose because terraform made key rotation for its releases, you should upgrade version according to support release, this article may help you https://www.scalefactory.com/blog/2021/04/30/hashicorp-terraform-release-key-rotation/

**Comment by bendbennett** [comment]
As mentioned by @wilmanestupinan, the solution in this instance is to upgrade to the latest patch version of the Terraform binary. Further details concerning GPG key rotation and the versions of updated binaries to use are available in
[Terraform Updates for HCSEC-2021-12](https://discuss.hashicorp.com/t/terraform-updates-for-hcsec-2021-12/23570).

If this problem persists, please open another issue providing as much detail as possible. Many thanks.
