### ISSUE TITLE
Cannot plan 3.2.0 random_password resources anymore

### ISSUE THREAD

**Issue by lra** [hashicorp/terraform-provider-random#261]
### Terraform CLI and Provider Versions

```
Terraform v1.2.2
on darwin_arm64
+ provider registry.terraform.io/hashicorp/random v3.3.0
```

### Terraform Configuration

```terraform
resource "random_password" "test" {
  length = 20
}
```

### Expected Behavior

Empty terraform plan when upgrading from `hashicorp/random v3.2.0` to `hashicorp/random v3.3.0`

### Actual Behavior

When planning after upgrading from v3.2.0 to v3.3.0 I get:
```
│ Error: state upgrade failed, number is not a boolean: <nil>
│ 
│   with random_password.test,
│   on temp-resources.tf line 1, in resource "random_password" "test":
│    1: resource "random_password" "test" {
│ 
```

### Steps to Reproduce

1. `terraform apply` using `hashicorp/random v3.2.0`
2. `terraform plan` using `hashicorp/random v3.3.0`

### How much impact is this issue causing?

Low

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bendbennett** [comment]
Hi @lra thank you for reporting this issue and sorry for any inconvenience.
I have tried to reproduce the issue you describe, but have been unable to do so using the following approaches.

### Specifying Required Provider
Running `terraform apply` with the following:

```terraform
terraform {
  required_providers {
    hashicorp-random = {
      source  = "hashicorp/random"
      version = "3.2.0"
    }
  }
}

resource "random_password" "test" {
  provider = hashicorp-random
  length = 20
}
```

Then running `terraform plan` with the following:

```terraform
terraform {
  required_providers {
    hashicorp-random = {
      source  = "hashicorp/random"
      version = "3.3.0"
    }
  }
}

resource "random_password" "test" {
  provider = hashicorp-random
  length = 20
}
```

### Using local overrides
Using the following in `~/.terraformrc`
```bash
provider_installation {

  dev_overrides {
        "hashicorp/random" = "/Users/bdb/go/bin"
  }

  # For all other providers, install them directly from their origin provider
  # registries as normal. If you omit this, Terraform will _only_ use
  # the dev_overrides block, and so no other providers will be available.
  direct {}
}
```

Then checking out `v3.2.0`, building locally with `make install` then running `terraform apply` using the following:

```terraform
resource "random_password" "test" {
  length = 20
}
```

Then checking out `v3.3.0`, building locally with `make install` then running `terraform plan` using the following:

```terraform
resource "random_password" "test" {
  length = 20
}
```

**Comment by bendbennett** [comment]
@lra did you by any chance import the password?
Are you able to share your `terraform.tfstate` file contents after you ran `terraform apply` using `hashicorp/random v3.2.0`?

**Comment by lra** [comment]
The issue is no more in v3.3.1, no need to spend time reproducing it. Thanks!
