### ISSUE TITLE
random_string function makes nose in the plan exposing the ID and override_special "" 

### ISSUE THREAD

**Issue by chanakanissanka** [hashicorp/terraform-provider-random#314]
### Terraform CLI and Provider Versions

Hi Team, 
Since the last version dropped, i.e. 3.4.2, our plan shows a noise [+override_special:         "" ] with exposed random string. We don't use this option. 
I have reverted to 3.4.1 and don't see this noise anymore normal as it supposes to be.  I just want to understand why this is happening. 

### Terraform Configuration

```terraform
our config is simple as this
resource "random_string" "base" {
  length  = 4
  special = false

}
```

### Expected Behavior

 don't want to see an additional noise on the plan with random strings and exposed random string characters

### Actual Behavior

![image](https://user-images.githubusercontent.com/40533683/188707440-15212ba0-8396-4377-bb23-6d1e377bbaf2.png)
 we can see this type of noise. This is just a sample and a bunch like this where this is used. 

### Steps to Reproduce

N/A ( Normally, since last 2nd, every TF plan shows this. ) 

### How much impact is this issue causing?

Medium

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bflad** [comment]
Hi @chanakanissanka 👋 Thank you for raising this and sorry you ran into trouble with this.

The planned fix for this, #310, is already merged and will be released sometime in the next day or so. Once that version is released, this attribute should not show the unexpected plan difference with `override_special` (unless it is applied with version 3.4.2, in which the upcoming release will show another plan to fix it back to `null` where it should remain stable again).

**Comment by chanakanissanka** [comment]
Thanks, @bflad, for the update. look forward to the merge. Cheers

**Comment by bflad** [comment]
Hi folks 👋 Version 3.4.3 of the provider was released and should resolve some of these cases. If you are still having trouble after upgrading, please reach out in a new issue and we can take a fresh look. Thanks.
