### ISSUE TITLE
Unclear what will be replaced in-line for random_string change

### ISSUE THREAD

**Issue by syphernl** [hashicorp/terraform-provider-random#316]
### Terraform CLI and Provider Versions

Terraform v1.2.9
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.75.2
+ provider registry.terraform.io/hashicorp/random v3.4.2

### Terraform Configuration

```terraform
resource "random_string" "rds_password" {
  length  = 32
  special = false
}
```

### Expected Behavior

A more clear explanation as to what will change, so that this change can be approved properly.

### Actual Behavior

Terraform only indicates the following:

```shell
Terraform will perform the following actions:

  # random_string.rds_password will be updated in-place
  ~ resource "random_string" "rds_password" {
        id          = "REDACTED"
        # (11 unchanged attributes hidden)
    }
```

Before and after there is a slight difference in the statefile (namely `override_special` and `sensitive_attributes`:

```json
{
      "mode": "managed",
      "type": "random_string",
      "name": "rds_password",
      "provider": "provider[\"registry.terraform.io/hashicorp/random\"]",
      "instances": [
        {
          "schema_version": 2,
          "attributes": {
            "id": "REDACTED",
            "keepers": null,
            "length": 32,
            "lower": true,
            "min_lower": 0,
            "min_numeric": 0,
            "min_special": 0,
            "min_upper": 0,
            "number": true,
            "numeric": true,
            "override_special": null,
            "result": "REDACTED",
            "special": false,
            "upper": true
          },
          "sensitive_attributes": [
            
          ],
          "private": "eyJzY2hlbWFfdmVyc2lvbiI6IjEifQ=="
        }
      ]
    },
```

After:

```json
    {
      "mode": "managed",
      "type": "random_string",
      "name": "rds_password",
      "provider": "provider[\"registry.terraform.io/hashicorp/random\"]",
      "instances": [
        {
          "schema_version": 2,
          "attributes": {
            "id": "REDACTED",
            "keepers": null,
            "length": 32,
            "lower": true,
            "min_lower": 0,
            "min_numeric": 0,
            "min_special": 0,
            "min_upper": 0,
            "number": true,
            "numeric": true,
            "override_special": "",
            "result": "REDACTED",
            "special": false,
            "upper": true
          },
          "sensitive_attributes": []
        }
      ]
    },
```

### Steps to Reproduce

1. `terraform apply` on Random < 3.4.0
2. `terraform apply` on Random >= 3.4.0

### How much impact is this issue causing?

Low

### Additional Information

This could be related to https://github.com/hashicorp/terraform-provider-random/issues/302

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bflad** [comment]
Hi @syphernl 👋 Thank you for raising this and apologies you ran into trouble here.

The provider unfortunately does not have any control about the plan difference output in this case as Terraform (due to some legacy reasons) is likely hiding the `override_special` attribute errantly going from `null` to `""` with version 3.4.2.

The good news though is that this should be resolved by upgrading to 3.4.3, which was recently released. If the resource happened to be applied with 3.4.2, it may show one more plan to go from `""` back to `null` then it'll stabilize. Additional reference: #312
