### ISSUE TITLE
random_password result may contain special characters not defined in override_special 

### ISSUE THREAD

**Issue by Yvand** [hashicorp/terraform-provider-random#337]
### Terraform CLI and Provider Versions

Terraform v1.3.5
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v3.25.0
+ provider registry.terraform.io/hashicorp/null v3.1.1
+ provider registry.terraform.io/hashicorp/random v3.4.3

### Terraform Configuration

```terraform
resource "random_password" "random_admin_password" {
  length           = 8
  special          = true
  override_special = "!#$%&*()-_=+[]{}<>:?"
}

output "admin_password" {
  value     = local.admin_password
  sensitive = true
}
```

### Expected Behavior

The result should contain a string, with special characters that are in the list specified by `override_special`

### Actual Behavior

The result contains special character `\`, while it is not defined in `override_special`
String generated: `"?c6ju\u0026q5"`

```shell
terraform state show random_password.random_admin_password
# random_password.random_admin_password:
resource "random_password" "random_admin_password" {
    bcrypt_hash      = (sensitive value)
    id               = "none"
    length           = 8
    lower            = true
    min_lower        = 0
    min_numeric      = 0
    min_special      = 0
    min_upper        = 0
    number           = true
    numeric          = true
    override_special = "!#$%&*()-_=+[]{}<>:?"
    result           = (sensitive value)
    special          = true
    upper            = true
}
```

### Steps to Reproduce

1. `terraform apply`
2. Inspect the outputs in the state file

### How much impact is this issue causing?

Medium

### Additional Information

Sometimes I'm not able to connect to the VMs using the password generated.
I believe that might be caused by the `\` character which randomly causes something unexpected. I would like to ensure that `\` is never used in the password string

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bendbennett** [comment]
Hi @Yvand 👋 
Thank you for raising this and sorry that you ran into trouble here.

I'm wondering if the issue might be because of the configuration that you're using.

In order to get `terraform apply` to run I had to modify the configuration that you supplied slightly, as follows:

```terraform
resource "random_password" "random_admin_password" {
  length           = 8
  special          = true
  override_special = "!#$%&*()-_=+[]{}<>:?"
}

output "admin_password" {
  value     = random_password.random_admin_password
  sensitive = true
}
```

With this configuration, if I then run `terraform apply` then I see the following in the state file:
```shell
  "outputs": {
    "admin_password": {
      "value": {
        "bcrypt_hash": "$2a$10$sK8YH6HXZX5KUw7deMfPsuoDs0xo27jWx5wrQtdt5zd2wWL.AoNxO",
        "id": "none",
        "keepers": null,
        "length": 8,
        "lower": true,
        "min_lower": 0,
        "min_numeric": 0,
        "min_special": 0,
        "min_upper": 0,
        "number": true,
        "numeric": true,
        "override_special": "!#$%\u0026*()-_=+[]{}\u003c\u003e:?",
        "result": "bu6h3fdg",
        "special": true,
        "upper": true
      },
      "type": [
        "object",
        {
          "bcrypt_hash": "string",
          "id": "string",
          "keepers": [
            "map",
            "string"
          ],
          "length": "number",
          "lower": "bool",
          "min_lower": "number",
          "min_numeric": "number",
          "min_special": "number",
          "min_upper": "number",
          "number": "bool",
          "numeric": "bool",
          "override_special": "string",
          "result": "string",
          "special": "bool",
          "upper": "bool"
        }
      ],
      "sensitive": true
    }
  },
  "resources": [
    {
      "mode": "managed",
      "type": "random_password",
      "name": "random_admin_password",
      "provider": "provider[\"registry.terraform.io/hashicorp/random\"]",
      "instances": [
        {
          "schema_version": 3,
          "attributes": {
            "bcrypt_hash": "$2a$10$sK8YH6HXZX5KUw7deMfPsuoDs0xo27jWx5wrQtdt5zd2wWL.AoNxO",
            "id": "none",
            "keepers": null,
            "length": 8,
            "lower": true,
            "min_lower": 0,
            "min_numeric": 0,
            "min_special": 0,
            "min_upper": 0,
            "number": true,
            "numeric": true,
            "override_special": "!#$%\u0026*()-_=+[]{}\u003c\u003e:?",
            "result": "bu6h3fdg",
            "special": true,
            "upper": true
          },
          "sensitive_attributes": []
        }
      ]
    }
  ],
```

Can you show the configuration that you are using for the generated password?
Are you using something along the lines of what is described in the [documentation](https://registry.terraform.io/providers/hashicorp/random/latest/docs/resources/password)?

For instance, are you using `random_password.random_admin_password.result` or `admin_password.result`?

**Comment by Yvand** [comment]
Indeed, I observe the same in my state file:
`"override_special": "!#$%\u0026*()-_=+[]{}\u003c\u003e:?"`
And this is because some of the special characters are unicode encoded, like the `&` as `\u0026`.
I wonder if this may explain why sometimes the password is not working. Maybe as a test/workaround I can try to remove the 3 special characters which get encoded in the state file (`&<>`) ?
Or did I miss/misunderstand something?

My config is very similar to [the documentation](https://registry.terraform.io/providers/hashicorp/random/latest/docs/resources/password) (same value for `override_special`):
```hcl
# In locals:
admin_password = var.admin_password == "" ? random_password.random_admin_password.result : var.admin_password


resource "random_password" "random_admin_password" {
  length           = 8
  special          = true
  override_special = "!#$%&*()-_=+[]{}<>:?"
}

resource "azurerm_windows_virtual_machine" "vm_dc" {
  name                     = local.config_dc["vmName"]
  computer_name            = local.config_dc["vmName"]
  location                 = azurerm_resource_group.rg.location
  resource_group_name      = azurerm_resource_group.rg.name
  network_interface_ids    = [azurerm_network_interface.nic_dc_0.id]
  size                     = local.config_dc["vmSize"]
  admin_username           = var.admin_username
  admin_password           = local.admin_password
  license_type             = local.license_type
  timezone                 = var.time_zone
  enable_automatic_updates = true
  provision_vm_agent       = true

  os_disk {
    name                 = "Disk-${local.config_dc["vmName"]}-OS"
    storage_account_type = local.config_dc["storageAccountType"]
    caching              = "ReadWrite"
  }

  source_image_reference {
    publisher = local.config_dc["vmImagePublisher"]
    offer     = local.config_dc["vmImageOffer"]
    sku       = local.config_dc["vmImageSKU"]
    version   = "latest"
  }
}


# In outputs:
output "admin_password" {
  value     = local.admin_password
  sensitive = true
}
```

Full source is here: https://github.com/Yvand/terraform-azurerm-sharepoint/tree/dev

**Comment by bendbennett** [comment]
Hi @Yvand 

Are the passwords that you are generating with the _random_ provider always meeting the criteria for `admin_password` for the `azurerm_windows_virtual_machine` resource?

Do you see any errors during `terraform apply`?
If so, could you link to a gist containing the output from running `TF_LOG=TRACE terraform apply`.

**MAKE SURE TO REMOVE ANY SENSITIVE DATA FROM THE GIST**

**Comment by bendbennett** [comment]
Hey @Yvand 

I just took a look at the link you provided for the full source https://github.com/Yvand/terraform-azurerm-sharepoint/tree/dev

I notice that the following statement appears in the README:

> Variables admin_password and service_accounts_password require a [strong password](https://learn.microsoft.com/azure/virtual-machines/windows/faq#what-are-the-password-requirements-when-creating-a-vm-), or they can be left empty to use an auto-generated password that will be recorded in the state file.

Looking at the link to [strong password](https://learn.microsoft.com/azure/virtual-machines/windows/faq#what-are-the-password-requirements-when-creating-a-vm-) I notice that it states the following:

> Portal - between 12 - 123 characters
PowerShell - between 8 - 123 characters
CLI - between 12 - 123
Have lower characters
Have upper characters
Have a digit
Have a special character (Regex match [\W_])

If all passwords **must** have upper and lower case characters, a digit and a special character then the configuration you're currently using for _random_password_ will sometimes fail to generate passwords that meet these criteria as you haven't set the `min_` fields.

For instance, if you want to ensure that the generated password contains at least one of each of the characters, you will need to alter your configuration along the following lines:

```terraform
resource "random_password" "random_admin_password" {
  length           = 8
  special          = true
  override_special = "!#$%&*()-_=+[]{}<>:?"
  min_lower = 1
  min_numeric = 1
  min_upper = 1
  min_special = 1
}
```

**Comment by Yvand** [comment]
@bendbennett you are absolutely correct regarding the password policy, thank you for catching this.
FYI I'm doing tests with `TF_LOG=TRACE` enabled and this new settings, to check if I can still reproduce the issue when the password contains a `\`.
I'll report back here asap

**Comment by Yvand** [comment]
@bendbennett thanks to your help now I have a consistent repro of the issue:
I modified the config as per your suggestion, and with a greater length:

```hcl

# In locals:
admin_password = var.admin_password == "" ? random_password.random_admin_password.result : var.admin_password

resource "random_password" "random_admin_password" {
  length           = 20
  special          = true
  override_special = "!#$%&*()-_=+[]{}<>:?"
  min_lower        = 1
  min_numeric      = 1
  min_upper        = 1
  min_special      = 1
}
```

Here is what was generated in the state file:
- `"override_special": "!#$%\u0026*()-_=+[]{}\u003c\u003e:?"`
- `admin_password` is `"GxB$\u003ez45\u003eh)$M4h\u0026\u0026mB\u003e"`

Using RDP to connect to the VM:
- This password does NOT work: `GxB$\u003ez45\u003eh)$M4h\u0026\u0026mB\u003e`
- This password works (I decoded the encoded unicode chars): `GxB$>z45>h)$M4h&&mB>`

The question that remains is: Is it expected that, in the result string recorded in the state file, special chars `&<>` are unicode encoded?

FYI: If needed, the gist TF_LOG is available here: https://gist.github.com/Yvand/c60ae6d4dc116f083bf87cda8fcfec7e

**Comment by bendbennett** [comment]
@Yvand I've checked with the maintainers of Terraform Core and can confirm that it is expected that `&<>` are encoded in the state file. 

The response I received was as follows:

> this is part of go's default JSON serialization, which quotes strings so that they're safe to embed in HTML:
https://pkg.go.dev/encoding/json#Marshal

> String values encode as JSON strings coerced to valid UTF-8, replacing invalid bytes with the Unicode replacement rune. So that the JSON will be safe to embed inside HTML <script> tags, the string is encoded using HTMLEscape, which replaces "<", ">", "&", U+2028, and U+2029 are escaped to "\u003c","\u003e", "\u0026", "\u2028", and "\u2029". This replacement can be disabled when using an Encoder, by calling SetEscapeHTML(false).

**Comment by Yvand** [comment]
@bendbennett thank you for the high quality support you provided, you were able to help me quickly and with very valuable insights
