### ISSUE TITLE
[Examples only] Updating random & null provider version constraint from 2.x to 3.x in the many terraform-aws-modules examples that use them

### ISSUE THREAD

**Issue by corzine** [hashicorp/terraform-provider-random#342]
### Terraform CLI and Provider Versions

Terraform v1.3.4
on darwin_arm64
+ provider registry.terraform.io/hashicorp/random _(current is v3.4.3 but the versions in questions start at 2.0.0)_
+ provider registry.terraform.io/hashicorp/null _(current is v3.2.1 but the versions in questions start at 2.0.0)_

### Summary
Update only those `examples/*/versions.tf` files in the terraform-aws-modules repos using `random` and `null` provider version constraints of 2.x to `>= 3.0.0`.

### Details:
* Many of the [terraform-aws-modules](https://github.com/terraform-aws-modules) used the [random](https://registry.terraform.io/providers/hashicorp/random/latest/docs) and/or [null](https://registry.terraform.io/providers/hashicorp/null/latest/docs) providers in their examples.
* Most of these set their version constraints to something like `>= 2.0`.
* At 3.0.0 the breaking changes for both `random` and `null` included going version 2 of the Terraform Plugin SDK (dropping support for 0.11).
* Almost of all these use `required_providers` blocks, this was introduced in 0.13.
* It is not clear if version 1 of the Terraform Plugin SDK is even supported in modern versions of Terraform.  The current discussion is about going from SDKv2 to Terraform Plugin Framework.  The SDKv1 that random & null v2.x depend on is clearly very old.
* v 3.x also introduced support for `linux-arm64` and `darwin-arm64`.
* I have tentatively identified 57 `versions.tf` files in the `examples/*` directories which contain the `random` or `null` providers.  It is possible I missed some as this was done by `egrep -A2 'random|null' */examples/*/versions.tf` in a directory with all of the modules cloned manually/individually.

### Background
This came up when I used one of the examples from one of the terraform-aws-modules and copied the random provider's version constraint of `>= 2.0`.  I then modified it to keep from going to the next major version w/o intervention by changing it to `>= 2.0, < 3.0.0` (which I understand to be a recommended practice).  `terraform init` then failed on my M1 Mac because no 2.x version supported it.

This was originally covered in #340 and @bendbennett asked for more information so it could be fixed.  I realized I had already done the prep work and am volunteering to do the next steps.

### Proposal

I am volunteering to prepare and submit all of the PRs to the various terraform-aws-modules that specify random & null provider v2.x.  I have already done the prep work, cloned all of the (non-archived) modules belonging to the terraform-aws-modules organization, greped the examples and have a list of the files needing changes.

I am proposing to change all of these examples random & version v2.x version constraints to `>= 3.0.0`.  No regular module code will be touched.

I will also look for uses of the `random` provider `b64` attribute that was dropped in v3.0.0 and had been deprecated before that.  This was the only other breaking change in either providers' CHANGELOG.md. (#118)

For testing I will perform a `terraform init` in each modified example (after removing any `.terraform.lock.hcl` files).  This should test the scope of this change.  I assume HashiCorp has more comprehensive testing in their CI pipelines.

Unless necessary, additional issues will not be created for this, only PRs which reference this issue.

### Attached is a list of all identified files, results of a grep across them, and a copy of the task list below
* [affected-files.txt](https://github.com/hashicorp/terraform-provider-random/files/10184567/affected-files.txt)
* [grep-results.txt](https://github.com/hashicorp/terraform-provider-random/files/10184569/grep-results.txt)
* [task-list.txt](https://github.com/hashicorp/terraform-provider-random/files/10184588/task-list.txt)

### A detailed task list of all of the files having the `random` or `null` providers (will be checked off as I submit the PRs)
- [ ] [terraform-aws-alb/examples/complete-alb/versions.tf](https://github.com/terraform-aws-modules/terraform-aws-alb/blob/master/examples/complete-alb/versions.tf)
- [ ] [terraform-aws-alb/examples/complete-nlb/versions.tf](https://github.com/terraform-aws-modules/terraform-aws-alb/blob/master/examples/complete-nlb/versions.tf)
- [ ] [terraform-aws-apigateway-v2/examples/complete-http/versions.tf](https://github.com/terraform-aws-modules/terraform-aws-apigateway-v2/blob/master/examples/complete-http/versions.tf)
- [ ] [terraform-aws-apigateway-v2/examples/vpc-link-http/versions.tf](https://github.com/terraform-aws-modules/terraform-aws-apigateway-v2/blob/master/examples/vpc-link-http/versions.tf)
- [ ] [terraform-aws-appsync/examples/complete/versions.tf](https://github.com/terraform-aws-modules/terraform-aws-appsync/blob/master/examples/complete/versions.tf)
- [ ] [terraform-aws-cloudfront/examples/complete/versions.tf](https://github.com/terraform-aws-modules/terraform-aws-cloudfront/blob/master/examples/complete/versions.tf)
- [ ] [terraform-aws-datadog-forwarders/examples/complete/versions.tf](https://github.com/terraform-aws-modules/terraform-aws-datadog-forwarders/blob/master/examples/complete/versions.tf)
- [ ] [terraform-aws-datadog-forwarders/examples/simple/versions.tf](https://github.com/terraform-aws-modules/terraform-aws-datadog-forwarders/blob/master/examples/simple/versions.tf)
- [ ] [terraform-aws-dms/examples/complete/versions.tf](https://github.com/terraform-aws-modules/terraform-aws-dms/blob/master/examples/complete/versions.tf)
- [ ] [terraform-aws-dynamodb-table/examples/autoscaling/versions.tf](https://github.com/terraform-aws-modules/terraform-aws-dynamodb-table/blob/master/examples/autoscaling/versions.tf)
- [ ] [terraform-aws-dynamodb-table/examples/basic/versions.tf](https://github.com/terraform-aws-modules/terraform-aws-dynamodb-table/blob/master/examples/basic/versions.tf)
- [ ] [terraform-aws-dynamodb-table/examples/global-tables/versions.tf](https://github.com/terraform-aws-modules/terraform-aws-dynamodb-table/blob/master/examples/global-tables/versions.tf)
- [ ] [terraform-aws-eks/examples/fargate_profile/versions.tf](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/fargate_profile/versions.tf)
- [ ] [terraform-aws-eks/examples/karpenter/versions.tf](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/karpenter/versions.tf)
- [ ] [terraform-aws-elb/examples/complete/versions.tf](https://github.com/terraform-aws-modules/terraform-aws-elb/blob/master/examples/complete/versions.tf)
- [ ] [terraform-aws-eventbridge/examples/api-gateway-event-source/versions.tf](https://github.com/terraform-aws-modules/terraform-aws-eventbridge/blob/master/examples/api-gateway-event-source/versions.tf)
- [ ] [terraform-aws-eventbridge/examples/complete/versions.tf](https://github.com/terraform-aws-modules/terraform-aws-eventbridge/blob/master/examples/complete/versions.tf)
- [ ] [terraform-aws-eventbridge/examples/default-bus/versions.tf](https://github.com/terraform-aws-modules/terraform-aws-eventbridge/blob/master/examples/default-bus/versions.tf)
- [ ] [terraform-aws-eventbridge/examples/with-api-destination/versions.tf](https://github.com/terraform-aws-modules/terraform-aws-eventbridge/blob/master/examples/with-api-destination/versions.tf)
- [ ] [terraform-aws-eventbridge/examples/with-archive/versions.tf](https://github.com/terraform-aws-modules/terraform-aws-eventbridge/blob/master/examples/with-archive/versions.tf)
- [ ] [terraform-aws-eventbridge/examples/with-ecs-scheduling/versions.tf](https://github.com/terraform-aws-modules/terraform-aws-eventbridge/blob/master/examples/with-ecs-scheduling/versions.tf)
- [ ] [terraform-aws-eventbridge/examples/with-lambda-scheduling/versions.tf](https://github.com/terraform-aws-modules/terraform-aws-eventbridge/blob/master/examples/with-lambda-scheduling/versions.tf)
- [ ] [terraform-aws-eventbridge/examples/with-permissions/versions.tf](https://github.com/terraform-aws-modules/terraform-aws-eventbridge/blob/master/examples/with-permissions/versions.tf)
- [ ] [terraform-aws-iam/examples/iam-eks-role/versions.tf](https://github.com/terraform-aws-modules/terraform-aws-iam/blob/master/examples/iam-eks-role/versions.tf)
- [ ] [terraform-aws-lambda/examples/alias/versions.tf](https://github.com/terraform-aws-modules/terraform-aws-lambda/blob/master/examples/alias/versions.tf)
- [ ] [terraform-aws-lambda/examples/async/versions.tf](https://github.com/terraform-aws-modules/terraform-aws-lambda/blob/master/examples/async/versions.tf)
- [ ] [terraform-aws-lambda/examples/build-package/versions.tf](https://github.com/terraform-aws-modules/terraform-aws-lambda/blob/master/examples/build-package/versions.tf)
- [ ] [terraform-aws-lambda/examples/code-signing/versions.tf](https://github.com/terraform-aws-modules/terraform-aws-lambda/blob/master/examples/code-signing/versions.tf)
- [ ] [terraform-aws-lambda/examples/complete/versions.tf](https://github.com/terraform-aws-modules/terraform-aws-lambda/blob/master/examples/complete/versions.tf)
- [ ] [terraform-aws-lambda/examples/container-image/versions.tf](https://github.com/terraform-aws-modules/terraform-aws-lambda/blob/master/examples/container-image/versions.tf)
- [ ] [terraform-aws-lambda/examples/deploy/versions.tf](https://github.com/terraform-aws-modules/terraform-aws-lambda/blob/master/examples/deploy/versions.tf)
- [ ] [terraform-aws-lambda/examples/event-source-mapping/versions.tf](https://github.com/terraform-aws-modules/terraform-aws-lambda/blob/master/examples/event-source-mapping/versions.tf)
- [ ] [terraform-aws-lambda/examples/multiple-regions/versions.tf](https://github.com/terraform-aws-modules/terraform-aws-lambda/blob/master/examples/multiple-regions/versions.tf)
- [ ] [terraform-aws-lambda/examples/simple/versions.tf](https://github.com/terraform-aws-modules/terraform-aws-lambda/blob/master/examples/simple/versions.tf)
- [ ] [terraform-aws-lambda/examples/triggers/versions.tf](https://github.com/terraform-aws-modules/terraform-aws-lambda/blob/master/examples/triggers/versions.tf)
- [ ] [terraform-aws-lambda/examples/with-efs/versions.tf](https://github.com/terraform-aws-modules/terraform-aws-lambda/blob/master/examples/with-efs/versions.tf)
- [ ] [terraform-aws-lambda/examples/with-vpc-s3-endpoint/versions.tf](https://github.com/terraform-aws-modules/terraform-aws-lambda/blob/master/examples/with-vpc-s3-endpoint/versions.tf)
- [ ] [terraform-aws-lambda/examples/with-vpc/versions.tf](https://github.com/terraform-aws-modules/terraform-aws-lambda/blob/master/examples/with-vpc/versions.tf)
- [ ] [terraform-aws-memory-db/examples/complete/versions.tf](https://github.com/terraform-aws-modules/terraform-aws-memory-db/blob/master/examples/complete/versions.tf)
- [ ] [terraform-aws-notify-slack/examples/cloudwatch-alerts-to-slack/versions.tf](https://github.com/terraform-aws-modules/terraform-aws-notify-slack/blob/master/examples/cloudwatch-alerts-to-slack/versions.tf)
- [ ] [terraform-aws-rds-aurora/examples/mysql/versions.tf](https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/blob/master/examples/mysql/versions.tf)
- [ ] [terraform-aws-rds-aurora/examples/postgresql/versions.tf](https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/blob/master/examples/postgresql/versions.tf)
- [ ] [terraform-aws-rds-aurora/examples/s3-import/versions.tf](https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/blob/master/examples/s3-import/versions.tf)
- [ ] [terraform-aws-rds-proxy/examples/mysql_iam_cluster/versions.tf](https://github.com/terraform-aws-modules/terraform-aws-rds-proxy/blob/master/examples/mysql_iam_cluster/versions.tf)
- [ ] [terraform-aws-rds-proxy/examples/mysql_iam_instance/versions.tf](https://github.com/terraform-aws-modules/terraform-aws-rds-proxy/blob/master/examples/mysql_iam_instance/versions.tf)
- [ ] [terraform-aws-rds-proxy/examples/postgresql_iam_cluster/versions.tf](https://github.com/terraform-aws-modules/terraform-aws-rds-proxy/blob/master/examples/postgresql_iam_cluster/versions.tf)
- [ ] [terraform-aws-rds-proxy/examples/postgresql_iam_instance/versions.tf](https://github.com/terraform-aws-modules/terraform-aws-rds-proxy/blob/master/examples/postgresql_iam_instance/versions.tf)
- [ ] [terraform-aws-rds/examples/s3-import-mysql/versions.tf](https://github.com/terraform-aws-modules/terraform-aws-rds/blob/master/examples/s3-import-mysql/versions.tf)
- [ ] [terraform-aws-redshift/examples/complete/versions.tf](https://github.com/terraform-aws-modules/terraform-aws-redshift/blob/master/examples/complete/versions.tf)
- [ ] [terraform-aws-s3-bucket/examples/complete-legacy/versions.tf](https://github.com/terraform-aws-modules/terraform-aws-s3-bucket/blob/master/examples/complete-legacy/versions.tf)
- [ ] [terraform-aws-s3-bucket/examples/complete/versions.tf](https://github.com/terraform-aws-modules/terraform-aws-s3-bucket/blob/master/examples/complete/versions.tf)
- [ ] [terraform-aws-s3-bucket/examples/notification/versions.tf](https://github.com/terraform-aws-modules/terraform-aws-s3-bucket/blob/master/examples/notification/versions.tf)
- [ ] [terraform-aws-s3-bucket/examples/object/versions.tf](https://github.com/terraform-aws-modules/terraform-aws-s3-bucket/blob/master/examples/object/versions.tf)
- [ ] [terraform-aws-s3-bucket/examples/s3-inventory/versions.tf](https://github.com/terraform-aws-modules/terraform-aws-s3-bucket/blob/master/examples/s3-inventory/versions.tf)
- [ ] [terraform-aws-s3-bucket/examples/s3-replication/versions.tf](https://github.com/terraform-aws-modules/terraform-aws-s3-bucket/blob/master/examples/s3-replication/versions.tf)
- [ ] [terraform-aws-step-functions/examples/complete/versions.tf](https://github.com/terraform-aws-modules/terraform-aws-step-functions/blob/master/examples/complete/versions.tf)
- [ ] [terraform-aws-vpc/examples/vpc-flow-logs/versions.tf](https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/master/examples/vpc-flow-logs/versions.tf)

### How much impact is this issue causing?

Low

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by corzine** [comment]
Is my proposal appropriate or should this be left to HashiCorp employees?

This is my first attempt at contributing to Terraform and I've only tried to contribute to Open Source projects via Github a few times before.  Have I done this correctly?

**Comment by corzine** [comment]
That list may look overwhelming but there are only 21 modules potentially affected (and some already use v3 of the providers).
[affected-files.txt](https://github.com/hashicorp/terraform-provider-random/files/10184810/affected-files.txt)

### Module Task List
- [ ] [terraform-aws-alb](https://github.com/terraform-aws-modules/terraform-aws-alb)
- [ ] [terraform-aws-apigateway-v2](https://github.com/terraform-aws-modules/terraform-aws-apigateway-v2)
- [ ] [terraform-aws-appsync](https://github.com/terraform-aws-modules/terraform-aws-appsync)
- [ ] [terraform-aws-cloudfront](https://github.com/terraform-aws-modules/terraform-aws-cloudfront)
- [ ] [terraform-aws-datadog-forwarders](https://github.com/terraform-aws-modules/terraform-aws-datadog-forwarders)
- [ ] [terraform-aws-dms](https://github.com/terraform-aws-modules/terraform-aws-dms)
- [ ] [terraform-aws-dynamodb-table](https://github.com/terraform-aws-modules/terraform-aws-dynamodb-table)
- [ ] [terraform-aws-eks](https://github.com/terraform-aws-modules/terraform-aws-eks)
- [ ] [terraform-aws-elb](https://github.com/terraform-aws-modules/terraform-aws-elb)
- [ ] [terraform-aws-eventbridge](https://github.com/terraform-aws-modules/terraform-aws-eventbridge)
- [ ] [terraform-aws-iam](https://github.com/terraform-aws-modules/terraform-aws-iam)
- [ ] [terraform-aws-lambda](https://github.com/terraform-aws-modules/terraform-aws-lambda)
- [ ] [terraform-aws-memory-db](https://github.com/terraform-aws-modules/terraform-aws-memory-db)
- [ ] [terraform-aws-notify-slack](https://github.com/terraform-aws-modules/terraform-aws-notify-slack)
- [ ] [terraform-aws-rds-aurora](https://github.com/terraform-aws-modules/terraform-aws-rds-aurora)
- [ ] [terraform-aws-rds-proxy](https://github.com/terraform-aws-modules/terraform-aws-rds-proxy)
- [ ] [terraform-aws-rds](https://github.com/terraform-aws-modules/terraform-aws-rds)
- [ ] [terraform-aws-redshift](https://github.com/terraform-aws-modules/terraform-aws-redshift)
- [ ] [terraform-aws-s3-bucket](https://github.com/terraform-aws-modules/terraform-aws-s3-bucket)
- [ ] [terraform-aws-step-functions](https://github.com/terraform-aws-modules/terraform-aws-step-functions)
- [ ] [terraform-aws-vpc](https://github.com/terraform-aws-modules/terraform-aws-vpc)

(end of list)

**Comment by bendbennett** [comment]
@corzine thank you for submitting a very thorough proposal.

The changes you are suggesting will need to be made on repositories that are maintained by the community.

It looks like the repositories you have listed are all associated with [Terraform AWS modules](https://github.com/terraform-aws-modules). 

I believe the PRs will need to be generated for each of the repositories in question. For instance the changes you are proposing for [terraform-aws-s3-bucket](https://github.com/terraform-aws-modules/terraform-aws-s3-bucket) will need to be raised as a PR for that repository.

**Comment by corzine** [comment]
Ok, thank you.

I didn't realize the [Terraform AWS modules](https://github.com/terraform-aws-modules) were community maintained, I thought they were "Official".  That explains why they're in a different Github Organization.

**Comment by bendbennett** [comment]
@corzine Thank you for going to the trouble of identifying where the updates to the examples need to be made. I'm going to close this issue as the changes you are proposing are on repositories that are community maintained rather than HashiCorp maintained.
