### ISSUE TITLE
vpc module erroring while initialize.

### ISSUE THREAD

**Issue by venkypotini** [hashicorp/terraform-provider-random#349]
### Terraform CLI and Provider Versions

terraform {
  required_version = ">= 1.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~>3.0"
    }
  }
}

### Terraform Configuration

```terraform
module "vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  version = "3.16.1"
###Input omitted####
}
```

### Expected Behavior

should install vpc module.

### Actual Behavior

terraform init
Initializing modules...
Downloading registry.terraform.io/terraform-aws-modules/vpc/aws 3.16.1 for vpc...
- vpc in .terraform\modules\vpc

Initializing the backend...

Initializing provider plugins...
- Finding hashicorp/aws versions matching ">= 2.65.0, ~> 3.0, >= 3.72.0, >= 3.73.0, >= 4.27.0"...
╷
│ Error: Failed to query available provider packages
│
│ Could not retrieve the list of available versions for provider hashicorp/aws: no available releases match the given
│ constraints >= 2.65.0, ~> 3.0, >= 3.72.0, >= 3.73.0, >= 4.27.0

### Steps to Reproduce

1. `terraform init`

### How much impact is this issue causing?

High

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bendbennett** [comment]
Hi @venkypotini 👋 

Sorry you ran into trouble here but it looks like you are trying to use the [AWS VPC Terraform Module](https://registry.terraform.io/modules/terraform-aws-modules/vpc/aws/latest). 

The [documentation](https://registry.terraform.io/modules/terraform-aws-modules/vpc/aws/latest) for the AWS VPC Terraform Module indicates that issues should be reported on https://github.com/terraform-aws-modules/terraform-aws-vpc/issues whereas you have reported an issue on the _terraform-provider-random_ repository. I am therefore going to close this issue.
