### ISSUE TITLE
random_shuffle crashes when result_count=0

### ISSUE THREAD

**Issue by leonseng** [hashicorp/terraform-provider-random#409]
### Terraform CLI and Provider Versions

$ terraform version
Terraform v1.3.6
on linux_amd64
+ provider registry.terraform.io/hashicorp/random v3.5.1

### Terraform Configuration

```terraform
resource "random_shuffle" "this" {
  input        = ["hello", "world"]
  result_count = 0
}
```

### Expected Behavior

`random_shuffle.this.result` should return an empty list.

### Actual Behavior

Provider crashes when running `terraform apply`

```
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to random_shuffle.subnet_ids, provider "provider[\"registry.terraform.io/hashicorp/random\"]" produced an unexpected new value: .result_count: was cty.NumberIntVal(0), but now cty.NumberIntVal(2).
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
````

### Steps to Reproduce

1. `terraform apply`

### How much impact is this issue causing?

High

### Logs

https://gist.github.com/leonseng/14969404cbb5fabc137c9e370ef84220

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bendbennett** [comment]
Hi @leonseng 👋 

Thank you for reporting this issue. I have added a triage label to mark this issue for upcoming discussion.
