### ISSUE TITLE
tyring to upgrade azurerm version but getting below error.

### ISSUE THREAD

**Issue by manyasinghallseg** [hashicorp/terraform-provider-random#468]
### Terraform CLI and Provider Versions

terraform provider is > 0.14
current azurerm version is 2.99.0
new version will be 3.50.0

### Terraform Configuration

```terraform
NA
```

### Expected Behavior

NA

### Actual Behavior

NA

### Steps to Reproduce

1. `terraform apply`

### How much impact is this issue causing?

High

### Additional Information

Initializing provider plugins...
- terraform.io/builtin/terraform is built in to Terraform
- Finding lseg.com/terraform/azuregaps versions matching "0.2.0"...
- Finding hashicorp/azurerm versions matching "2.99.0, 3.50.0"...
- Finding latest version of hashicorp/null...
- Finding latest version of dome9/dome9...
- Installing dome9/dome9 v1.21.0...
- Installed dome9/dome9 v1.21.0 (unauthenticated)
- Installing lseg.com/terraform/azuregaps v0.2.0...
- Installed lseg.com/terraform/azuregaps v0.2.0 (unauthenticated)
- Installing hashicorp/null v3.2.1...
- Installed hashicorp/null v3.2.1 (self-signed, key ID 343[65](https://gitlab.dx1.lseg.com/app-00815/azu-subscription-spoke/-/jobs/13019423#L65)D9472D74[68](https://gitlab.dx1.lseg.com/app-00815/azu-subscription-spoke/-/jobs/13019423#L68)F)
Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/cli/plugins/signing.html
Error: Failed to query available provider packages
Could not retrieve the list of available versions for provider
hashicorp/azurerm: no available releases match the given constraints 2.99.0,
3.50.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bendbennett** [comment]
Hi @manyasinghallseg 👋 

Sorry you ran into trouble here. 

Can I just confirm that the issue you are encountering relates to the _random_ provider?

There doesn't seem to be any mention of the _random_ provider in the information that you supplied. At firt glance, the error appears to be related to the constraints you're using for the `azurerm` provider.

**Comment by bflad** [comment]
Closing due to lack of response.
