### ISSUE TITLE
random_string could support import

### ISSUE THREAD

**Issue by jaysonsantos** [hashicorp/terraform-provider-random#62]
### Terraform Version
Terraform v0.12.1

### Affected Resource(s)
- random_string
### Terraform Configuration Files
```hcl
resource "random_string" "master_password" {
  length = 16
}

resource "aws_rds_cluster" "cluster" {
  master_password = random_string.master_password.result
}
```

### Expected Behavior
It would be nice to be able to import random strings when you already have things like an RDS cluster set-up otherwise you need to change the password after the first import happens (if you want to keep the password on the state to be able to rotate).

### Actual Behavior
Import is denied

### Steps to Reproduce
1. `terraform random_string.master_password 1234`

If you think this would be useful, let me know and I can try to implement it.

**Comment by dijitali** [comment]
Agreed.  A lot of modules in the community make use of the `random_string` to ensure naming uniqueness.  As a result the resources in the modules depending on the `random_string` must be recreated on state import, which is a pain!

**Comment by crisp2u** [comment]
https://github.com/terraform-providers/terraform-provider-random/pull/46

**Comment by dekimsey** [comment]
This would be amazing but also for the `random_password` resource. We need to migrate some uses of random_string to random_password but I'm wary of doing that since it'll regenerate the values.

**Comment by nijave** [comment]
You can achieve this by pulling down the state, manually editing, and pushing back up although importing would be ideal

**Comment by jahantech** [comment]
Is this solution acceptabled? 
PR: https://github.com/terraform-providers/terraform-provider-random/pull/100 
Any comments will be appreciated.

**Comment by gespinoza22** [comment]
Concur on support for import on random_string and random random_password

**Comment by Sytten** [comment]
Can this provider be released so we have access to this feature. Thanks.

**Comment by skolsuper** [comment]
Seems like this was released and works nicely, thanks!  Can close this issue now 👍
