### ISSUE TITLE
random_id docs give the wrong number of bytes for UUID-equivalence

### ISSUE THREAD

**Issue by apparentlymart** [hashicorp/terraform-provider-random#9]
The `random_id` docs claim the following:

> Unlike other resources in the "random" provider, this resource does use a cryptographic random number generator in order to minimize the chance of collisions, making the results of this resource when a 32-byte identifier is requested of equivalent uniqueness to a type-4 UUID.

This is misleading because a UUID is actually 16 bytes. The _hex representation_ is 32-bytes.

**Comment by bflad** [comment]
I believe this was handled awhile ago with https://github.com/hashicorp/terraform-provider-random/pull/41 😄
